Fixed gradle wrapper files
Regenerated the Gradle wrapper using "gradle wrapper"
and granted execute permissions to the resulting gradlew
file to allow running "./gradlew build" in this project.

Prior to this fix, "./gradlew build" failed with the
error:

How can I set this package up so that I can successfully run "./gradlew build"?

Right now this command fails with the error:

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

while "gradle build" worked without errors.